[tool.poetry]
name = "cheeto"
version = "0.1.0"
description = "Utilities for the UC Davis HPC Core Facility."
license = "Proprietary"
authors = [
	"Camille Scott <cswel@ucdavis.edu"
]
readme = "README.md"
repository = "https://github.com/ucdavis/cheeto"

