[tool.poetry]
name = "cheeto"
version = "0.1.0"
description = "Utilities for the UC Davis HPC Core Facility."
license = "Proprietary"
authors = [
	"Camille Scott <cswel@ucdavis.edu>"
]
readme = "README.md"
repository = "https://github.com/ucdavis/cheeto"

[tool.poetry.scripts]
cheeto = "cheeto.__main__:main"

[tool.poetry.dependencies]
python = "^3.10"
mashumaro = {extras = ["yaml"], version = "^3.5"}
rich = "^13.3.1"
ruamel-yaml = "^0.17.21"
marshmallow-dataclass = {extras = ["union"], version = "^8.5.12"}
mergedeep = "^1.3.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
